@@grammar::FORMULAS

start =
    expression $
    ;

expression =
    | expression '&' factor
    | expression '|' factor
    | expression '=>' factor
    | expression '<=>' factor
    | factor
    ;

factor =
    | '(' expression ')'
    | variable
    ;

variable =
    /[ABCDEFGHIJKLMNOPQRSTUVWXYZ]/
    ;
