
all: HelloWorld.class DynLoad.class Injected.class

HelloWorld.class: HelloWorld.java
	javac HelloWorld.java

Injected.class: Injected.java
	javac Injected.java

DynLoad.class: DynLoad.java
	javac DynLoad.java

clean:
	rm *.class 2>/dev/null
