#!/bin/bash

all:

install-mipsel32:
	cp ./test.bntl ~/repos/vector35/binaryninja/typelib/mipsel32/libc.so.0.bntl
	cp ./test.bntl ~/repos/vector35/binaryninja/build_debug/out/binaryninja.app/Contents/Resources/typelib/mipsel32/libc.so.0.bntl
	cp ./test.bntl ~/repos/vector35/binaryninja/build_release/out/binaryninja.app/Contents/Resources/typelib/mipsel32/libc.so.0.bntl

uninstall-mipsel32:
	rm -f ~/repos/vector35/binaryninja/typelib/mipsel32/libc.so.0.bntl
	rm -f ~/repos/vector35/binaryninja/build_debug/out/binaryninja.app/Contents/Resources/typelib/mipsel32/libc.so.0.bntl
	rm -f ~/repos/vector35/binaryninja/build_release/out/binaryninja.app/Contents/Resources/typelib/mipsel32/libc.so.0.bntl


